import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { Login } from '../../../public/login'
import styles from '../../../styles/Home.module.css'


const defaultEndpoint = "https://vef2-20222-v3-synilausn.herokuapp.com/events";


export async function getServerSideProps({ query }){
    const {id} =query;
    const res = await fetch(`${defaultEndpoint}/${id}`);
    const data = await res.json();
    return{
        props:{
          data
        }
    }
}

let comment = '';

const Event: NextPage = ({ data}) => {
  const { name, created, description, creatorid, updated} = data;
  const {registrations = []} = data;
  const {id} = data;
  let loggedin;
  const [registered, setRegistered] = useState(false);

  const onRegister = (e) => {
    e.preventDefault();
    registerevent(e);

    async function registerevent(e) {
      e.preventDefault();

      const body = {
        comment: comment
      };
      
      
      const req = {
          mode: 'cors',
          method: 'POST',
          headers: {
            "Authorization": `Bearer ${window.localStorage.getItem('token')}`,
          },
          body: JSON.stringify(body)
      }
      const resp = await fetch(`${defaultEndpoint}/${id}/register`,req);
      const data = await resp.json();
      console.log(JSON.stringify(req));
      console.log(`${defaultEndpoint}/${id}`)
      setRegistered(true);
    }
  }

  if(typeof window !== 'undefined'){
    if(window.localStorage.getItem("token")){
      loggedin = true;
    }
    else loggedin = false;
  }

  return (

    <div className={styles.container}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          {name}
        </h2>
        <h3 className={styles.footers}>{description}</h3>
        
        <div className={styles.regs}>
        <h2 className={styles.footers}>Skráningar:</h2>
        

        {registrations.length === 0 && (
          <p className={styles.footers}>Engin hefur skráð sig á þennan viðburð</p>
        )}

        {registrations.length > 0 && (
        <ul className={styles.registrations}>
          {registrations.map((item: { id: any; username: any; name: any; comment: any }) =>{
            const{id, username ,name, comment} = item;
            
            return(
              <li key ={id} className={styles.registration}>
                <h3 className={styles.regname}>{name}</h3>
                {JSON.stringify(comment).length < 100 && (
                  <p className={styles.regcom}>{comment}</p>)}
                
              </li>
            )

          })}
          
        </ul>
        )}
        </div>

        {registered && (<p className={styles.footers}>Þú hefur skráð þig á þennan viðburð</p>)}


        
      {!registered && (
        <>
          {loggedin && (
            <form className={styles.footers} onSubmit={onRegister}>
              <h3>Skráningarform:</h3>
              <label>Athugasemd</label><br></br>
              <textarea  className={styles.inputbox} id="comment" name="comment" />
              <br></br>
              <button>Skrá mig</button>
              <p>&nbsp;</p>
            </form>
          )}

          {!loggedin && (
            <p className={styles.footers}>Skráðu þig inn til að skrá þig á viðburðinn</p>
          )}
        </>
      )}

      <hr></hr>
        <div>
          <Login>
            
          </Login>
        </div>  
        
        <p className={styles.back}> 
        <Link href="/">
          <a>
            Til baka á Forsíðu
          </a>
        </Link>
        </p>   
       
      </main>

      
    </div>
  )
}

export default Event
