import type { NextPage } from 'next'
import Head from 'next/head'

import Moment from "moment";
import  Link  from 'next/link';
import styles from '../styles/Home.module.css'
import { Login } from '../public/login'

const defaultEndpoint = "https://vef2-20222-v3-synilausn.herokuapp.com/events";

export async function getServerSideProps(){
    const res = await fetch(defaultEndpoint);
    const data = await res.json();
    return{
        props:{
          data
        }
    }
}


const Home: NextPage = ({data}:{data:any}) => {
  const {items = []} = data;
  
  return (

    <div className={styles.container}>
      <Head>
        <title>Viðburðarsíðan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Viðburðarsíðan
        </h1>

        <p className={styles.description}>
         Viðburðir:
        </p>
       
        <ul className={styles.grid}>
          {items.map((item: { id: any; name: any; description: any; created: any; }) =>{
            const { id, name, description, created} = item;
            
            return ( 
            <li key ={id} className={styles.card}>
              <Link href="/events[id]" as={`/events/${id}`}>
              <a>
                <h2>{name}</h2>
                <p className={styles.eventdesc}>{description}</p>
                <h3>{Moment(created).format('d MMM YYYY hh:mm:ss')}</h3>
              </a>
              </Link>
            </li>      
            )
          })}
             
        </ul>
        <>
        <hr></hr>
        <div>
          <Login>

          </Login>
        </div>
        </>
        
      </main>

      
    </div>
  )
}

export default Home
