import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { MouseEvent } from 'react'
import styles from '../styles/Home.module.css'
import {useRouter} from 'next/router'



const defaultEndpoint = "https://vef2-20222-v3-synilausn.herokuapp.com/users/login";


var username = '';
var password = '';

export async function getServerSideProps(){
    
    const req = await fetch(defaultEndpoint);
    const data = await req.json();
    return{
        props:{
          data
        }
    }
}



const Login: NextPage = ({data}) => {
  
  const router = useRouter();

  async function tryLogIn(e){
    e.preventDefault();


    const body = {
        username: username,
        password: password
    }
    const req = {
        mode: 'cors' as RequestMode,
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify(body)
    }
    const resp = await fetch(defaultEndpoint,req);
    const data = await resp.json();
    console.log(data);
    localStorage.setItem('token', data.token)
    router.push('/');
}

  return (

    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.forms}>
        <h2 className={styles.title}>
          Innskráning
        </h2>
        <form className={styles.form}>
        <div className="field">
                <label>Notendanafn</label>
                <br></br>
                <input type="text" name="username" id="username" onChange={e => username = e.target.value}></input>
            </div>
        <div className="field">
            <label>Lykilorð</label>
            <br></br>
            <input type="password" name="password" id="password" onChange={e => password = e.target.value}></input>
        </div>
            <button className={styles.button} onClick={e => tryLogIn(e)}>Innskrá</button>
        </form>

      <p>&nbsp;</p>
        
        <p className={styles.backa}> 
        <Link href="/">
          <a>
            Til baka á Forsíðu
          </a>
        </Link>
        </p>   
       
      </main>

      
    </div>
  )
}

export default Login