import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'


const defaultEndpoint = "https://vef2-20222-v3-synilausn.herokuapp.com/users/register";

export async function getServerSideProps(){
    
    const res = await fetch(defaultEndpoint);
    const data = await res.json();
    return{
        props:{
          data
        }
    }
}


let name ='';
let username ='';
let password = '';

async function tryRegister(e){
  e.preventDefault();

  const body = {
      name: name,
      username: username,
      password: password
  }

  if(body.password.length > 5){

  }
  const req = {
      mode: 'cors',
      method: 'POST',
      headers: {
          'Content-Type': 'application/json',
      },
      body: JSON.stringify(body)
  }
  const resp = await fetch(defaultEndpoint,req);
  const data = await resp.json();
  console.log(data);
  localStorage.setItem('token', data.token)
}


const Register: NextPage = () => {
  
  
  return (

    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.forms}>
        <h2 className={styles.title}>
          Nýskráning
        </h2>
        <form className={styles.form}>
        <div className="field">
              <label>Nafn</label>
              <br></br>
              <input type="text" name="name" id="name" onChange={e => name = e.target.value}></input>
        </div>
        <div className="field">
              <label>Notendanafn</label>
              <br></br>
              <input type="text" name="username" id="username" onChange={e => username = e.target.value}></input>
        </div>
        <div className="field">
            <label>Lykilorð</label>
            <br></br>
            <input className={styles.inputbox} type="password" name="password" id="password" placeholder="10 stafir min" onChange={e => password = e.target.value}></input>
        </div>
            <button className={styles.button} onClick={e => tryRegister(e)}>Nýskrá</button>
        </form>

      <p>&nbsp;</p>
        
        <p className={styles.backa}> 
        <Link href="/">
          <a>
            Til baka á Forsíðu
          </a>
        </Link>
        </p>   
       
      </main>

      
    </div>
  )
}

export default Register